---
language: ruby
sudo: false
rvm:
  - 2.2.2
  - 2.3.0
  - 2.4.0
script:
  - bundle install
  - gem install vcloud-core
  - ./scripts/setfog.sh
  - bundle exec rake integration
notifications:
  email: false
